In [1]:
from PIL import Image

## Create an RBG Image

In [2]:
# Create a New Orange Image
image = Image.new(mode="RGB",size=(100,100),color=(255,100,0))
print(image)

<PIL.Image.Image image mode=RGB size=100x100 at 0x120462E20>


In [3]:
print(type(image))
print(image.size)
print(image.mode)
print(image.getbands())

<class 'PIL.Image.Image'>
(100, 100)
RGB
('R', 'G', 'B')


In [4]:
print(image.show())

None


# Create an B/W Image

In [5]:
bw_image = Image.new(mode='L', size=(100,100), color=(100))
print(bw_image)

<PIL.Image.Image image mode=L size=100x100 at 0x120976910>


In [6]:
print(type(bw_image))
print(bw_image.size)
print(bw_image.mode)
print(bw_image.getbands())

<class 'PIL.Image.Image'>
(100, 100)
L
('L',)


In [7]:
print(bw_image.show())

None


## Create an Image using OpenCV & Numpy

In [8]:
import numpy as np
import cv2

In [12]:
image_open_cv_bw = np.zeros((500,500,1),dtype=np.uint8)
image_open_cv_bw[:] = (140)
print(image_open_cv_bw)

[[[140]
  [140]
  [140]
  ...
  [140]
  [140]
  [140]]

 [[140]
  [140]
  [140]
  ...
  [140]
  [140]
  [140]]

 [[140]
  [140]
  [140]
  ...
  [140]
  [140]
  [140]]

 ...

 [[140]
  [140]
  [140]
  ...
  [140]
  [140]
  [140]]

 [[140]
  [140]
  [140]
  ...
  [140]
  [140]
  [140]]

 [[140]
  [140]
  [140]
  ...
  [140]
  [140]
  [140]]]


In [13]:
print(image_open_cv_bw.shape)

(500, 500, 1)


In [ ]:
cv2.imshow("Grey Scale Image", image_open_cv_bw)
cv2.waitKey(0)
cv2.destroyAllWindows()