In [1]:
!pip install numpy

/Users/chandu/Desktop/ML_Learnings/datascience/venv/bin/pip: line 2: /Users/chandu/Desktop/ML Learnings/datascience/venv/bin/python3: No such file or directory
/Users/chandu/Desktop/ML_Learnings/datascience/venv/bin/pip: line 2: exec: /Users/chandu/Desktop/ML Learnings/datascience/venv/bin/python3: cannot execute: No such file or directory


In [2]:
import numpy as np

In [3]:
#create 1D array 
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [22]:
#Reshape 1D array as 2D array
arr2 = np.array([1,2,3,4,5])
arr2 = arr2.reshape(1,5)
print(arr2)
print(type(arr2))
print(arr2.shape)
print(arr2.ndim)
print(arr2.dtype)
print(arr2.size)
print(arr2.itemsize)


[[1 2 3 4 5]]
<class 'numpy.ndarray'>
(1, 5)
2
int64
5
8


In [13]:
arr3 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr3)

[[1 2 3 4 5]
 [2 3 4 5 6]]


In [14]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [15]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [17]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
# Identity matrix
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
# Vectorisation in Numpy 
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

# Element wise Addition
print("Addition", arr1+arr2)

Addition [11 22 33 44 55]


In [27]:
# Some Inbuild/Universal Functions
print(np.sqrt(arr1))
print(np.exp(arr1))
print(np.log(arr1))
print(np.sin(arr1))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [28]:
# Array Slicing and Indexing
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
arr[0][0]

1

In [32]:
arr[1][2:]

array([7, 8])

In [36]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [41]:
#stats concepts -- normalisation ie., mean is 0  and standard deviation is 1

arr = [1,2,3,4,5]

#Mean 
print("Mean:", np.mean(arr))
#Standard deviation
print("standard deviation:", np.std(arr))

# Normalisation
normalised_data = (arr - np.mean(arr))/np.std(arr)
print("normalised_data:", normalised_data)


Mean: 3.0
standard deviation: 1.4142135623730951
normalised_data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [49]:
#Logical Operation 
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [50]:
arr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [51]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])